---
- hosts: elk
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - group_vars/all.yml
  roles:
    - { role: elasticsearch }
    - { role: logstash }
    - { role: kibana }
    - { role: xpack, when: ((install_elasticsearch_xpack|bool) or (install_kibana_xpack|bool) or (install_logstash_xpack|bool)) }
    - { role: firewall, when: manage_firewall|bool }
    - { role: instructions }
