---
#
# install/run heartbeatbeat elk client
#
- name: Copy templated elasticsearch.repo
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644
  become: true

- name: Install heartbeat rpms
  yum:
    name: heartbeat-elastic
  become: true

- name: Generate heartbeat configuration template
  template:
    src=heartbeat.yml.j2
    dest=/etc/heartbeat/heartbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  register: heartbeat_needs_restart

- name: Start heartbeat service
  command: systemctl start heartbeat-elastic.service
  ignore_errors: true
  become: true
  when: ((heartbeat_needs_restart != 0) and (logging_backend != 'fluentd'))

- name: Setup heartbeat service
  service: name=heartbeat-elastic state=started enabled=true
  become: true
