---
- hosts: all
  roles:
    - { role: setup }
    - { role: java }
    - { role: elasticsearch }
    - { role: logstash }
    - { role: kibana }
    - { role: xpack, when: ((install_elasticsearch_xpack|bool) or (install_kibana_xpack|bool) or (install_logstash_xpack|bool)) }
    - { role: firewall, when: manage_firewall|bool }
    - { role: instructions }
