---
#
# print informational messages
#
- name: Restart elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: true
  become: true

- name: Restart Logstash
  systemd:
    name: logstash
    state: started
    enabled: true
  become: true

- name: Restart Kibana
  systemd:
    name: kibana
    state: started
    enabled: true
  become: true

- name: Print SSL certificate post-setup information
  debug: msg="Filebeat SSL Certificate available at http://{{ ansible_fqdn }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.crt"

- name: Print SSL key post-setup information
  debug: msg="Filebeat SSL Certificate key is located at http://{{ ansible_fqdn }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.key"

- name: Print X-Pack instructions
  debug: msg="*** 1A) (X-Pack only) Kibana account credentials login with elastic/{{xpack_elastic_user_password}} ***"
  when: install_kibana_xpack|bool

- name: Print index creation instructions
  debug: msg="*** 1) Navigate to http://{{ ansible_fqdn }}:{{ kibana_server_port }} and login with {{kibana_user}}/{{kibana_password}} ***"
