---
- name: Include vars
  include_vars:
    file: group_vars/all.yml

- name: Copy templated kibana.repo
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0644
  become: true

- name: Install rsyslog and dependencies
  yum:
    name: rsyslog
    state: present
  become: true

- name: Install kibana rpms
  yum:
    name: kibana
    state: present
  become: true

- name: Copy templated kibana.yml
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: 0644
  become: true

- name: Copy kibana systemd config
  template:
    src: systemd.j2
    dest: /etc/systemd/system/kibana.service
    owner: kibana
    group: kibana
    mode: 0644
  become: true

- name: Create Kibana log file
  file:
    path: /var/log/kibana.log
    state: touch
    owner: kibana
    group: kibana
    mode: 0644
  become: true

- name: Enable kibana service
  systemd:
    name: kibana
    enabled: yes
  become: true

- name: Check Filebeat forwarder SSL certificate
  stat:
    path: /usr/share/logstash/beat-forwarder.crt
  ignore_errors: true
  register: filebeat_forwarder_ssl_exists
  become: true

- name: Create client forwarder SSL certificate
  command: openssl req -subj '/CN={{ ansible_fqdn }}/' -config /etc/pki/tls/openssl_extras.cnf \
    -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /usr/share/logstash/beat-forwarder.key \
    -out /usr/share/logstash/beat-forwarder.crt
  ignore_errors: true
  when: (filebeat_forwarder_ssl_exists != 0)
  become: true

#- name: Start kibana service
#  service:
#    name: kibana
#    state: started
#  become: true
