---
- name: ensure that firewalld is running
  service:
    name: firewalld
    state: started
    enabled: yes
  ignore_errors: yes
  register: firewalld_check

  register: firewalld_status
- import_tasks: firewalld.yml
  when: firewalld_check is succeed
  #when: firewalld_check.stdout.find("running") != -1

- import_tasks: iptables.yml
  when: firewalld_check is failed 
  #when: firewalld_check.stdout.find("running") == -1
