---
- name: "ADD LOGSTASH FIREWALLD TCP PORT {{logstash_syslog_port}}"
  firewalld:
   port: "{{logstash_syslog_port}}/tcp"
   zone: public
   permanent: true
   state: enabled
  become: true

- name: "ADD ELASTIC FIREWALLD TCP PORT {{es_local_port}}"
  firewalld:
   port: "{{es_local_port}}/tcp"
   zone: public
   permanent: true
   state: enabled
  become: true

- name: "ADD KIBANA FIREWALLD TCP PORT {{kibana_server_port}}"
  firewalld:
   port: "{{kibana_server_port}}/tcp"
   zone: public
   permanent: true
   state: enabled
  become: true

- name: "ADD FIREWALLD TCP PORT {{elk_server_ssl_cert_port}} FOR SSL "
  firewalld:
   port: "{{elk_server_ssl_cert_port}}/tcp"
   zone: public
   permanent: true
   state: enabled
  become: true
#  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 7
# END telegraf FIREWALLD PORT

- name: RELOAD FIREWALLD
  systemd:
    name: firewalld
    state: reloaded
  become: true
