---
#
# Install/run elasticsearch
#
- name: Include vars
  include_vars:
    file: group_vars/all.yml

- name: Install libsemanage-python and dependencies
  yum:
    name: libsemanage-python
  become: true

- name: Copy templated elasticsearch.repo 
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0644
  become: true

- name: Install elasticsearch and openjdk
  yum:
    name: [elasticsearch, java-openjdk-headless]
    state: present
  become: true

- name: Copy templated elasticsearch.yml
  template:
    src: "elasticsearch.yml.j2"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: elasticsearch
    group: elasticsearch
    mode: 0660
  become: true

- name: Change file ownership of {{ es_path_data }}
  file:
    path: "{{ es_path_data }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
  become: true

- name: Change file ownership of {{ es_path_logs }}
  file:
    path: "{{ es_path_logs }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
  become: true

- name: Setup elasticsearch service to autostart
  systemd:
    name: elasticsearch
    state: started
    enabled: true
  become: true
